language: c++

before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install g++-multilib gcc-multilib
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install openfl > /dev/null
  - haxelib install lime > /dev/null
  - haxelib install hxcpp > /dev/null
  - haxelib install actuate > /dev/null
  - haxelib install box2d > /dev/null
  - haxelib install swf > /dev/null
  - haxelib install layout > /dev/null
  - haxelib install format > /dev/null
  - mkdir ~/haxegon
  - cd ~/haxegon
  - wget https://raw.githubusercontent.com/Decad/github-downloader/master/github-downloader.sh
  - ls
  - sudo ~/haxegon/github-downloader.sh https://github.com/TerryCavanagh/haxegon-samples/tree/master/simple/01%20-%20hello%20world
  - git clone --recursive https://github.com/terrycavanagh/haxegon ~/haxegon/src --depth 1
  
script:
  - ls
  - haxelib run openfl build $(pwd) flash
  - haxelib run openfl build $(pwd) html5
  - haxelib run openfl build $(pwd) neko
